ignored = ["github.com/impactasaurus/soq/tools"]

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "v0.6.0"

[[constraint]]
  name = "github.com/vektah/gqlparser"
  revision = "f119686bf1d4d1a68c7ed6afe35f183625443c41"



[prune]
  go-tests = true
  unused-packages = true

