[[constraint]]
  name = "github.com/apex/gateway"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"

[prune]
  go-tests = true
  unused-packages = true
