name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch: ~

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make test
      - name: Generate Production Files
        run: make build
      - name: Upload build artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: ./.build_output/lambda
          if-no-files-found: error
  deploy:
    name: Deploy App
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: bin
      - name: Zip
        run: chmod +x ./lambda && zip lambda.zip lambda
      - name: Deploy
        uses: appleboy/lambda-action@v0.1.3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: soq
          zip_file: ./lambda.zip
